sudo: false
language: java
jdk:
  - oraclejdk8

install:
  - pip install --user html5validator

script:
  - html5validator --root .

notifications:
  email: false
  webhooks:
    - https://snr.zulipchat.com/api/v1/external/travis?stream=cs181&topic=website&api_key=WtywO4mJ77FMN0HYebZIt4KYB23uNVcT
